baseURL = 'https://ymsimplelife.github.io/'
languageCode = 'en-us'
title = 'yuemachi simplelife Blog'
theme = 'hugo-theme-stack'
publishDir = "docs"
enableRobotsTXT = true
enableEmoji  = "true"
enableGitInfo = "true"
googleAnalytics = "G-7YQ4LLT67S"

[frontmatter]
  lastmod = [":git", "lastmod", "date", "publishDate"]

[Params]
	likerID = "yuemachi"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.8